listlistdev/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ListListDev.Models
{
    public class ErrorViewModel
    {
        public string errorMsg { get; set; }

        public ErrorViewModel()
        { }

        public ErrorViewModel(string message)
        {
            this.errorMsg = message;
        }
    }
}

listlistdev/ViewModels/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ListListDev.ViewModels
{
    public class ErrorViewModel
    {
        public string errorMsg { get; set; }

        public ErrorViewModel()
        { }

        public ErrorViewModel(string message)
        {
            this.errorMsg = message;
        }
    }
}

listlistdev/ViewModels/ListViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using ListListDev.Models;
using ListListDev.ViewModels;

namespace ListListDev.ViewModels
{
    public class DashboardViewModel
    {
        public List<ListHeader> Lists { get; set; }

        public DashboardViewModel()
        {
            this.Lists = new List<ListHeader>();
        }

        public DashboardViewModel(List<ListHeader> lists)
        {
            this.Lists = lists;
        }
    }

    public class CreateListHeaderViewModel
    {
        [Required(ErrorMessage = "You must enter a list title")]
        [StringLength(25)]
        [DisplayName("List Title")]
        public string Title { get; set; }
    }

    public class EditListHeaderViewModel
    {
        [Required(ErrorMessage = "You must enter a list title")]
        [StringLength(25)]
        [DisplayName("List Title")]
        public string Title { get; set; }
        public int ID { get; set; }

        public EditListHeaderViewModel()
        { }

        public EditListHeaderViewModel(ListHeader list)
        {
            this.Title = list.Title;
            this.ID = list.ID;
        }
    }

    public class CreateListItemViewModel
    {
        [Required(ErrorMessage = "You must enter a name for the item")]
        [StringLength(150)]
        [DisplayName("List Item Text")]
        public string Text { get; set; }
        public int ListHeaderID { get; set; }

        public CreateListItemViewModel()
        { }

        public CreateListItemViewModel(int id)
        {
            this.ListHeaderID = id;
        }
    }

    public class EditListItemViewModel
    {
        [Required(ErrorMessage = "You must enter a name for the item")]
        [StringLength(150)]
        [DisplayName("List Item Text")]
        public string Text { get; set; }
        public int ListHeaderID { get; set; }
        public int ID { get; set; }

        public EditListItemViewModel()
        { }

        public EditListItemViewModel(ListItem model)
        {
            this.Text = model.Text;
            this.ListHeaderID = model.ListHeaderID;
            this.ID = model.ID;
        }
    }
}

listlistdev/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ListListDev.DAL;
using ListListDev.Models;
using ListListDev.ViewModels;
using ListListDev.Logic;

namespace ListListDev.Controllers
{
    // Require a user to be logged in before being able to view/edit lists
    [Authorize]
    public class ListController : Controller
    {
        // Access to the logic for ListList
        private ListLogic _logic = new ListLogic();

        // Show error page (default message is "Unknown Error")
        public ActionResult Error(string message = "Unknown Error")
        {
            // Create view model with the provided error message
            var viewModel = new ErrorViewModel(message);
            return View(viewModel);
        }

        // Default page is the dashboard
        public ActionResult Index()
        {
            return RedirectToAction(nameof(Dashboard));
        }

        // Show all lists that belong to the user
        public ActionResult Dashboard()
        {
            // Get lists that belong to user
            List<ListHeader> lists = _logic.GetDashboardLists(User.Identity.GetUserId());

            if (lists != null)
            {
                var viewModel = new DashboardViewModel(lists);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction(nameof(Error),
                                            new { message = "There was an error accessing your lists." });
            }
        }

        #region ListHeader Actions

        [HttpGet]
        public ActionResult CreateListHeaderPartial()
        {
            var viewModel = new CreateListHeaderViewModel();
            return PartialView("~/Views/List/_CreateListHeaderForm.cshtml", viewModel);
        }

        [HttpPost]
        public ActionResult CreateListHeader(CreateListHeaderViewModel model)
        {
            // Check that the form submitted is valid
            if (ModelState.IsValid)
            {
                // Create the new list and save to the database
                ListHeader list = new ListHeader(model, User.Identity.GetUserId());

                // Try to save the new list to the database
                if (_logic.CreateListHeader(list))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
                else
                {
                    return RedirectToAction(nameof(Error),
                                                new { message = "There was an error creating your list." });
                }
            }
            else
            {
                // Form data wasn't valid so return user to the form
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult EditListHeaderPartial(int? id)
        {
            // Make sure an id was passed in
            if (id != null)
            {
                // Get the list from the database
                ListHeader list = _logic.GetListHeader(id.Value, User.Identity.GetUserId());

                if (list != null)
                {
                    var viewModel = new EditListHeaderViewModel(list);
                    return PartialView("~/Views/List/_EditListHeaderForm.cshtml", viewModel);
                }
            }

            return PartialView("~/Views/List/_Error.cshtml");
        }

        [HttpPost]
        public ActionResult EditListHeader(EditListHeaderViewModel model)
        {
            // Check that the form submitted is valid
            if (ModelState.IsValid)
            {
                ListHeader list = new ListHeader(model, User.Identity.GetUserId());

                // Try to save changes to the list
                if (_logic.EditListHeader(list))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
                else
                {
                    return RedirectToAction(nameof(Error),
                                                new { message = "There was an error saving your changes for the list name." });
                }
            }
            else
            {
                // Form data wasn't valid so return user to the form
                return View(model);
            }
        }

        public ActionResult DeleteListHeader(int? id)
        {
            // Make sure an id was passed in
            if (id != null)
            {
                // Try to delete the list from the database
                if (_logic.DeleteListHeader(id.Value, User.Identity.GetUserId()))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
            }

            return RedirectToAction(nameof(Error),
                                        new { message = "There was an error deleting the list." });
        }
        #endregion

        #region ListItems Actions

        [HttpGet]
        public ActionResult CreateListItemPartial(int? id)
        {
            // Make sure an id was passed in
            if (id != null)
            {
                // Make sure the user is allowed to add items to the list
                if (_logic.ListItemBelongsToUser(id.Value, User.Identity.GetUserId()))
                {
                    var viewModel = new CreateListItemViewModel(id.Value);
                    return PartialView("~/Views/List/_CreateListItemForm.cshtml", viewModel);
                }
            }

            return PartialView("~/Views/List/_Error.cshtml");
        }

        [HttpPost]
        public ActionResult CreateListItem(CreateListItemViewModel model)
        {
            // Check that the form submitted is valid
            if (ModelState.IsValid)
            {
                // Create a ListItem using the model received
                ListItem listItem = new ListItem(model);

                // Try to add list item to the database
                if (_logic.CreateListItem(listItem, User.Identity.GetUserId()))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
                else
                {
                    return RedirectToAction(nameof(Error),
                                                new { message = "There was an error creating the list item." });
                }
            }
            else
            {
                // Form data wasn't valid so return user to the form
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult EditListItemPartial(int? id)
        {
            // Make sure an id was passed in
            if (id != null)
            {
                // Get the list item from the database
                ListItem itemToEdit = _logic.GetListItem(id.Value, User.Identity.GetUserId());

                // Check that list item exists
                if (itemToEdit != null)
                {
                    var viewModel = new EditListItemViewModel(itemToEdit);
                    return PartialView("~/Views/List/_EditListItemForm.cshtml", viewModel);
                }
            }

            return PartialView("~/Views/List/_Error.cshtml");
        }

        [HttpPost]
        public ActionResult EditListItem(EditListItemViewModel model)
        {
            // Check that the form submitted is valid
            if (ModelState.IsValid)
            {
                // Create new ListItem using the model received
                ListItem item = new ListItem(model);

                // Try to save changes to the dastabase
                if (_logic.EditListItem(item, User.Identity.GetUserId()))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
                else
                {
                    return RedirectToAction(nameof(Error),
                                                new { message = "There was an error saving your changes for the list item text." });
                }
            }
            else
            {
                // Form data wasn't valid so return user to the form
                return View(model);
            }
        }

        public ActionResult DeleteListItem(int? id)
        {
            // Make sure an id was passed in
            if (id != null)
            {
                // Try to delete item from the database
                if (_logic.DeleteListItem(id.Value, User.Identity.GetUserId()))
                {
                    return RedirectToAction(nameof(Dashboard));
                }
            }

            return RedirectToAction(nameof(Error),
                                    new { message = "There was an error deleting the list item." });
        }

        #endregion
    }
}

listlistdev/Views/List/Dashboard.cshtml
@model ListListDev.ViewModels.DashboardViewModel
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";

    AjaxOptions AjaxOptions = new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "ajaxDiv",
        InsertionMode = InsertionMode.Replace,
        OnComplete = "showAjaxModal"
    };
}

<div class="row">
    <div class="col-md-12" align="center">
        <div align="left" id="dashboard">
            @if (Model.Lists.Count().Equals(0))
            {
                <div class="alert alert-info" role="alert" align="center">
                    You have no lists yet. Click the "Create New List" button to start!
                </div>
            }
            else
            {
                foreach (var list in Model.Lists)
                {
                    <div class="panel panel-default">
                        <div class="panel-heading clearfix">
                            <div class="pull-right">
                                @Ajax.ActionLink("Add List Item",
                                                 "CreateListItemPartial", 
                                                 new { list.ID }, AjaxOptions, 
                                                 new { @class = "btn btn-primary btn-sm" })
                                <button type="button" class="btn btn-danger btn-sm" 
                                        data-toggle="modal" data-target="#deleteModal" 
                                        onclick="deleteListHeader('@list.ID', '@list.Title');">
                                    Delete List
                                </button>
                            </div>
                            <h3 class="panel-title" style="padding-top: 7px;">
                                @list.Title 
                                <span style="font-size: 12px;">
                                    @Ajax.ActionLink(" ", "EditListHeaderPartial",
                                                    new { list.ID }, AjaxOptions,
                                                    new { @class = "glyphicon glyphicon-edit",
                                                          @style = "text-decoration: none;",
                                                          @title = "Edit List Name" })
                                </span>
                            </h3> 
                        </div>
                        <div class="panel-body">
                            @if (list.ListItems.Count().Equals(0))
                            {
                                <div class="alert alert-info" role="alert" style="margin: 0;">
                                    There are no items in this list.
                                </div>
                            }
                            else
                            {
                                <ul class="list-group" style="margin-bottom: 0px;">
                                    @foreach (var listItem in list.ListItems)
                                    {
                                        <li class="list-group-item clearfix">
                                            <div class="btn-group pull-right" role="group">
                                                <a class="btn btn-default btn-sm "
                                                    data-ajax="true" data-ajax-complete="showAjaxModal"
                                                    data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#ajaxDiv"
                                                    href="/List/EditListItemPartial/@listItem.ID" type="button">
                                                    <i class="glyphicon glyphicon-edit"></i>
                                                </a>
                                                <button type="button" class="btn btn-danger btn-sm" 
                                                        data-toggle="modal" data-target="#deleteModal" 
                                                        onclick="deleteListItem('@listItem.ID', '@listItem.Text');">
                                                    <i class="glyphicon glyphicon-trash"></i>
                                                </button>
                                            </div>
                                            <h5 style="padding-top: 7.5px; margin: 0;">@listItem.Text</h5>
                                        </li>
                                    }
                                </ul>
                            }
                        </div>
                    </div>
                }
            }
            @Ajax.ActionLink("Create New List", "CreateListHeaderPartial", null, AjaxOptions, new { @class = "btn btn-primary pull-right" })
        </div>
    </div>
</div>

<!-- Delete Confirmation Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog custom-modal-size" role="dialog">
        <div class="modal-content">
            <div class="modal-body" id="deleteModalBody">
                <p id="deleteWarning"></p>
            </div>
            <div class="modal-footer" id="deleteModalFooter">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a href="#" class="btn btn-danger" id="delBtn">Delete</a>
            </div>
        </div>
    </div>
</div>

<!-- Create/Edit List Item and List Header Modal -->
<div class="modal fade" id="ajaxModal" tabindex="-1" role="dialog">
    <div class="modal-dialog custom-modal-size" role="form">
        <div class="modal-content">
            <div id="ajaxDiv"></div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/dashboard")
}

listlistdev/Views/List/_CreateListHeaderForm.cshtml
@model ListListDev.ViewModels.CreateListHeaderViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create New List</h4>
</div>
<div class="modal-body clearfix">
    @using (Html.BeginForm("CreateListHeader", "List", FormMethod.Post, new { role = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "Enter List Name..." })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="pull-right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <input type="submit" value="Create List" class="btn btn-primary" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

listlistdev/Views/List/_CreateListItemForm.cshtml
@model ListListDev.ViewModels.CreateListItemViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create New List Item</h4>
</div>
<div class="modal-body clearfix">
    @using (Html.BeginForm("CreateListItem", "List", FormMethod.Post, new { role = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Text, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.Text, new { @class = "form-control", @placeholder = "Enter Item Name..."})
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.ListHeaderID)
        </div>

        <div class="pull-right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <input type="submit" value="Create Item" class="btn btn-primary" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

listlistdev/Views/List/_EditListHeaderForm.cshtml
@model ListListDev.ViewModels.EditListHeaderViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Edit List Name</h4>
</div>
<div class="modal-body clearfix">
    @using (Html.BeginForm("EditListHeader", "List", FormMethod.Post, new { role = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Title)
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.ID)
        </div>

        <div class="pull-right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

listlistdev/Views/List/_EditListItemForm.cshtml
@model ListListDev.ViewModels.EditListItemViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Edit List Item</h4>
</div>
<div class="modal-body clearfix">
    @using (Html.BeginForm("EditListItem", "List", FormMethod.Post, new { role = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Text)
            @Html.TextBoxFor(model => model.Text, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.ListHeaderID)
        </div>

        <div class="pull-right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

listlistdev/Views/List/_Error.cshtml
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Error</h4>
</div>
<div class="modal-body clearfix">
    <p>There was an error processing your action. Please try again.</p>
    <button type="button" class="btn btn-primary pull-right" data-dismiss="modal">Close</button>
</div>